# Generated by Django 5.1.4 on 2026-08-01 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_type', models.CharField(choices=[('Solo', 'Solo'), ('Family', 'Family'), ('Friends', 'Friends'), ('Business', 'Business'), ('Couple', 'Couple')], default='Solo', max_length=20)),
                ('hotel_preference', models.CharField(choices=[('Budget', 'Budget'), ('Standard', 'Standard'), ('Luxury', 'Luxury')], default='Standard', max_length=20)),
                ('transport', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Flight', 'Flight'), ('Car', 'Car')], default='Flight', max_length=20)),
                ('travelers', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(default=list, help_text='[{morning, afternoon, evening, night}, ...]')),
                ('hotels', models.JSONField(default=list)),
                ('restaurants', models.JSONField(default=list)),
                ('attractions', models.JSONField(default=list)),
                ('packing_tips', models.JSONField(default=list)),
                ('travel_tips', models.JSONField(default=list)),
                ('emergency_contacts', models.TextField(blank=True)),
                ('weather_suggestions', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True, help_text='Full raw text returned by Gemini, kept for debugging.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.trip')),
            ],
        ),
    ]
